version: "3.9"
services:
  go:
    image: go-holidays-server
    container_name: "${GO_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: go.Dockerfile
    environment:
      GO_INTERNAL_PORT: ${GO_INTERNAL_PORT}
      POSTGRES_CONTAINER_NAME: ${POSTGRES_CONTAINER_NAME}
      POSTGRES_INTERNAL_PORT: ${POSTGRES_INTERNAL_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${GO_EXTERNAL_PORT}:${GO_INTERNAL_PORT}"
    networks:
      go-postgres-bridge:
    depends_on:
      - postgres-db


  postgres-db:
    image: postgres:latest
    container_name: "${POSTGRES_CONTAINER_NAME}"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.schema.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2.data.sql

    networks:
      go-postgres-bridge:

networks:
  go-postgres-bridge:
    name: go-postgres-bridge
    driver: bridge
